"""empty message

Revision ID: 903db0158e2f
Revises: a911267cc557
Create Date: 2023-03-19 02:07:49.445850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903db0158e2f'
down_revision = 'a911267cc557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('course_code')

    # ### end Alembic commands ###
